name: Krupke

channels:
  - conda-forge

dependencies:
  # conda_core
  - python=3.10
  - numpy=1.24*
  - numba
  - scipy
  - pandas
  - scikit-image
  - opencv
  - scikit-learn
  - joblib
  - matplotlib-base
  - pip
  # conda_spec
  - napari
  - pyqt
  - spyder
  # conda_tf_nogpu
  - pip:
    # pip_core
    - bd-tools
    # pip_spec
    - readlif
    # pip_tf_nogpu
    - albumentations
    - segmentation-models
    - tensorflow==2.10
    - h5py==3.11.0